spring.config.import=optional:file:.env[.properties]
spring.application.name=arquiteconvencionales

# Configuración de Base de Datos
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA e Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:false}

# Thymeleaf
spring.thymeleaf.cache=${SPRING_THYMELEAF_CACHE:false}
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Servidor
server.port=${PORT:9090}
server.error.include-message=always
server.error.include-binding-errors=always