spring.config.import=optional:file:.env[.properties]
spring.application.name=arquiteconvencionales

spring.datasource.url=${LOCAL_DB_URL:${SPRING_DATASOURCE_URL}}
spring.datasource.username=${LOCAL_DB_USER:${SPRING_DATASOURCE_USERNAME}}
spring.datasource.password=${LOCAL_DB_PASSWORD:${SPRING_DATASOURCE_PASSWORD}}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:false}

spring.thymeleaf.cache=${SPRING_THYMELEAF_CACHE:false}
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

server.port=${SERVER_PORT:9090}
server.error.include-message=always
server.error.include-binding-errors=always
